### ISSUE TITLE
Throw all this inside of a Rails app?

### ISSUE THREAD

**Issue by Ross-Hunter** [CrashsLanding/petfinder-client#1]
We originally intended to have a client/server architecture, but we weren't thinking about ease of deployment onto a single heroku dyno at that time. One solution would be wrap the current code in a rails app using something like https://github.com/shakacode/react_on_rails. Existing sinatra logic could be translated to Rails pretty simply, and I am hoping the react code would also be basically good to go.

The other would be to containerize(?) what exists and write some build scripts.

Thoughts?

**Comment by KevinGreene** [comment]
I would be interested in that, definitely.

**Comment by Ross-Hunter** [comment]
So I don't think moving it into a rails app is actually going to improve the situation, except for maybe making it easier for others to hop into.

I'm not planning on railsifying this app, but I have been doing some other good stuff over in the other repo.
